export const PERMISSAO_GERENCIAR_USUARIOS = "GerenciarUsuarios";
export const PERMISSAO_GERENCIAR_CARGOS = "GerenciarCargos";
export const PERMISSAO_GERENCIAR_COMERCIO = "GerenciarComercio";
export const PERMISSAO_GERENCIAR_ASSINATURA = "GerenciarAssinatura";
export const PERMISSAO_GERENCIAR_PAGAMENTOS = "GerenciarPagamentos";
export const PERMISSAO_VISUALIZAR_RELATORIOS = "VisualizarRelatorios";

export const PERMISSOES_GESTAO = [
  PERMISSAO_GERENCIAR_USUARIOS,
  PERMISSAO_GERENCIAR_CARGOS,
  PERMISSAO_GERENCIAR_COMERCIO,
  PERMISSAO_GERENCIAR_ASSINATURA,
  PERMISSAO_GERENCIAR_PAGAMENTOS,
  PERMISSAO_VISUALIZAR_RELATORIOS,
];
